"""add doctors, appointments, visit_records tables

Revision ID: 2ab99cab8d92
Revises: b71783b6832e
Create Date: 2026-06-30 15:44:34.185753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab99cab8d92'
down_revision: Union[str, Sequence[str], None] = 'b71783b6832e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('doctor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason_for_visit', sa.String(length=255), nullable=True),
    sa.Column('xray_needed', sa.Boolean(), nullable=False),
    sa.Column('blood_test_needed', sa.Boolean(), nullable=False),
    sa.Column('is_urgent_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.String(length=255), nullable=True),
    sa.Column('rescheduled_to_appointment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['rescheduled_to_appointment_id'], ['appointments.appointment_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('visit_records',
    sa.Column('visit_record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_notes', sa.String(length=1000), nullable=True),
    sa.Column('treatment_status', sa.String(length=20), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ),
    sa.PrimaryKeyConstraint('visit_record_id'),
    sa.UniqueConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_records')
    op.drop_table('appointments')
    op.drop_table('doctors')
    # ### end Alembic commands ###
