"""add server defaults to boolean and status columns

Revision ID: 54c77154ea9e
Revises: faf2c35cd6ee
Create Date: 2026-06-30 16:27:33.013941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c77154ea9e'
down_revision: Union[str, Sequence[str], None] = 'faf2c35cd6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default='20',
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default='scheduled',
               existing_nullable=False)
    op.alter_column('appointments', 'xray_needed',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('appointments', 'blood_test_needed',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('appointments', 'is_urgent_override',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('patients', 'consent_given',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'consent_given',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('appointments', 'is_urgent_override',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('appointments', 'blood_test_needed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('appointments', 'xray_needed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('appointments', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
